logging.level.org.reflections=WARN
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.model-and-view-allowed=true
springdoc.packages-to-scan=com.velihangozek.payment.web
springdoc.paths-to-match=/api/**